AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deno Lambda with Oak server and API Gateway

Resources:
  DenoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deno-oak-api
      CodeUri: ./build/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DENO_RUNTIME: true
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  DenoFunction:
    Description: "Deno Lambda Function ARN"
    Value: !GetAtt DenoFunction.Arn
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
